dependencies:
  # - <organization/repo>@<version>
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
dotenv: .env
networks:
  default: development
  rinkeby:
    verify: True
    account: chrome
  ganache-local:
    verify: False
  polygon-test-2:
    account: chrome
  polygon-main-2:
    account: chrome
